import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import '../../components/layout/Layout.css';

const FAQ_DATA = [
  {
    category: 'Getting Started',
    questions: [
      {
        q: 'What do I need to play on La Bolita?',
        a: 'You need: (1) A cryptocurrency wallet like MetaMask, (2) USDT tokens on the Polygon network, and (3) A small amount of MATIC for transaction fees. That\'s it!'
      },
      {
        q: 'How do I get USDT on Polygon?',
        a: 'You can: (1) Bridge USDT from Ethereum or other networks using the Polygon Bridge, (2) Buy USDT directly on exchanges that support Polygon withdrawals (like Binance, Kraken, or Coinbase), or (3) Swap other tokens for USDT on decentralized exchanges like QuickSwap or Uniswap.'
      },
      {
        q: 'Is there a minimum deposit or bet?',
        a: 'There is no deposit - the platform is non-custodial. Minimum bets are 1 USDT for all games. La Fortuna tickets cost 1 USDT each.'
      },
      {
        q: 'What is a non-custodial platform?',
        a: 'Non-custodial means we never hold your funds. All transactions happen directly between your wallet and our smart contracts on the blockchain. You always maintain full control of your money.'
      }
    ]
  },
  {
    category: 'Games & Betting',
    questions: [
      {
        q: 'What games are available?',
        a: 'We offer two games: La Bolita (number betting with 2, 3, or 4 digit numbers) and La Fortuna (lottery-style game with 6 numbers + key number).'
      },
      {
        q: 'When are draws held?',
        a: 'La Bolita draws happen 3 times daily: 10:00, 15:00, and 21:00 UTC. La Fortuna draws are twice weekly: Wednesday and Saturday at 20:00 UTC.'
      },
      {
        q: 'What are the maximum bets?',
        a: 'For La Bolita, you can bet up to 1,000 USDT per number per draw. For La Fortuna, you can buy up to 8 tickets per transaction.'
      },
      {
        q: 'Can I bet on multiple numbers?',
        a: 'Yes! You can place multiple bets in a single transaction, each on different numbers or game types.'
      }
    ]
  },
  {
    category: 'Prizes & Payouts',
    questions: [
      {
        q: 'How do I know if I won?',
        a: 'Check the Results page after each draw. Your wallet address will show any prizes you\'ve won. You can also view your betting history in your profile.'
      },
      {
        q: 'How do I claim my winnings?',
        a: 'For La Bolita wins, you can claim directly from the smart contract. For La Fortuna, larger draws may use a Merkle tree claim system - you\'ll receive a proof to claim your prize.'
      },
      {
        q: 'Is there a deadline to claim prizes?',
        a: 'Yes, prizes must be claimed within 90 days of the draw. After that, unclaimed prizes return to the prize pool.'
      },
      {
        q: 'What is the jackpot cap?',
        a: 'The La Fortuna jackpot has a cap of $1,000,000 USDT. When reached, additional contributions go to the prize pool instead.'
      }
    ]
  },
  {
    category: 'Fairness & Security',
    questions: [
      {
        q: 'How do I know the results are fair?',
        a: 'We use Chainlink VRF (Verifiable Random Function) for all results. This is a cryptographically secure random number generator that provides proof of fairness. See our Provably Fair page for details.'
      },
      {
        q: 'Can La Bolita manipulate results?',
        a: 'No. Results are generated by Chainlink VRF, a decentralized oracle network. There is no function in our smart contracts to manually set or override results. This is verifiable on the blockchain.'
      },
      {
        q: 'Are the smart contracts audited?',
        a: 'Our contracts are built using OpenZeppelin standards and are verified on PolygonScan. The source code is open for anyone to review.'
      },
      {
        q: 'Is my wallet safe?',
        a: 'We never have access to your private keys or seed phrase. Always keep these secure and never share them with anyone. We will never ask for your private keys.'
      }
    ]
  },
  {
    category: 'Technical',
    questions: [
      {
        q: 'Which wallets are supported?',
        a: 'Any wallet that supports the Polygon network works with La Bolita. We recommend MetaMask, but WalletConnect, Coinbase Wallet, and others also work.'
      },
      {
        q: 'Why do I need MATIC?',
        a: 'MATIC is the native token of Polygon and is required to pay for transaction fees (gas). Don\'t worry - Polygon fees are very low, typically less than $0.01 per transaction.'
      },
      {
        q: 'My transaction is stuck. What do I do?',
        a: 'Polygon transactions usually confirm within seconds. If stuck, try: (1) Increasing gas price in your wallet, (2) Waiting a few minutes for network congestion to clear, or (3) Checking the transaction status on PolygonScan.'
      },
      {
        q: 'What happens if the website goes down?',
        a: 'Your funds are safe on the blockchain, not on our servers. You can always interact directly with the smart contracts using PolygonScan or another interface.'
      }
    ]
  },
  {
    category: 'Legal & Restrictions',
    questions: [
      {
        q: 'Is La Bolita legal?',
        a: 'Online gambling laws vary by jurisdiction. It is your responsibility to ensure that using La Bolita complies with your local laws. We restrict access from certain countries - see our Restricted Jurisdictions page.'
      },
      {
        q: 'Which countries are restricted?',
        a: 'We restrict access from the US, UK, Spain, France, Germany, Italy, Netherlands, Belgium, and several other countries. See our full list on the Restricted Jurisdictions page.'
      },
      {
        q: 'Can I use a VPN to access from a restricted country?',
        a: 'No. Attempting to circumvent geographic restrictions is a violation of our Terms of Service and may result in forfeiture of any winnings.'
      },
      {
        q: 'What is the minimum age to play?',
        a: 'You must be at least 18 years old, or the legal gambling age in your jurisdiction, whichever is higher.'
      }
    ]
  }
];

function FAQPage() {
  const [openItems, setOpenItems] = useState({});

  const toggleItem = (categoryIndex, questionIndex) => {
    const key = `${categoryIndex}-${questionIndex}`;
    setOpenItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div className="info-page">
      <h1>Frequently Asked Questions</h1>
      <p className="page-subtitle">
        Find answers to common questions about La Bolita.
      </p>

      {FAQ_DATA.map((category, catIndex) => (
        <div key={catIndex} style={{ marginBottom: '2rem' }}>
          <h2>{category.category}</h2>
          {category.questions.map((item, qIndex) => {
            const key = `${catIndex}-${qIndex}`;
            const isOpen = openItems[key];
            return (
              <div key={qIndex} className="faq-item">
                <div
                  className="faq-question"
                  onClick={() => toggleItem(catIndex, qIndex)}
                >
                  <span>{item.q}</span>
                  <span style={{ color: '#FFD700' }}>{isOpen ? '−' : '+'}</span>
                </div>
                {isOpen && (
                  <div className="faq-answer">
                    <p>{item.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ))}

      <h2>Still Have Questions?</h2>
      <p>
        Can't find what you're looking for? Visit our <Link to="/contact" style={{ color: '#FFD700' }}>Contact</Link> page
        or join our <a href="https://t.me/labolita" target="_blank" rel="noopener noreferrer" style={{ color: '#FFD700' }}>Telegram community</a>.
      </p>
    </div>
  );
}

export default FAQPage;
